// ─────────────────────────────────────────────────────────────────────────────
// scene_lut.sv  —  Compile-time scene LUT (11 spheres + 1 light)
//
// Generated by Scene LUT Editor
// Matches c-implementation/scene.h exactly (Q16.16 values)
//
// Sphere encoding:
//   - center (cx, cy, cz)
//   - radius
//   - color (r, g, b) as 8-bit integers (0-255)
//   - reflectivity (Q16.16, 0.0 to 1.0)
//
// Light encoding:
//   - position (lx, ly, lz)
//   - color (r, g, b) as 8-bit integers (0-255)
//   - intensity (Q16.16, typically 1.5 = 98304)
// ─────────────────────────────────────────────────────────────────────────────

`timescale 1ns/1ps
`default_nettype none

package scene_lut;
    // Scene counts
    localparam NUM_SPHERES = 11;
    localparam NUM_LIGHTS  = 1;

    typedef struct packed {
        logic signed [31:0] cx, cy, cz;
        logic signed [31:0] radius;
        logic [7:0] colorR, colorG, colorB;
        logic signed [31:0] reflectivity;
    } sphere_t;

    typedef struct packed {
        logic signed [31:0] lx, ly, lz;
        logic [7:0] colorR, colorG, colorB;
        logic signed [31:0] intensity;
    } light_t;

    // Table-driven scene data (update this section only)
    localparam sphere_t SPHERES [0:NUM_SPHERES-1] = '{
        '{ cx:-32'sd33186  , cy:32'sd33645   , cz:32'sd393216 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 },
        '{ cx:-32'sd70358  , cy:32'sd69454   , cz:32'sd393216 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 },
        '{ cx:-32'sd90605  , cy:32'sd113190  , cz:32'sd393216 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 },
        '{ cx:-32'sd84148  , cy:32'sd163028  , cz:32'sd393216 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 },
        '{ cx:-32'sd49710  , cy:32'sd204089  , cz:32'sd393216 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 },
        '{ cx:-32'sd6401   , cy:32'sd221670  , cz:32'sd393216 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 },
        '{ cx:32'sd45270   , cy:32'sd199406  , cz:32'sd393216 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 },
        '{ cx:32'sd0       , cy:-32'sd40459  , cz:32'sd393216 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 },
        '{ cx:32'sd0       , cy:32'sd1484    , cz:32'sd393216 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 },
        '{ cx:32'sd0       , cy:-32'sd84876  , cz:32'sd393216 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 },
        '{ cx:32'sd0       , cy:-32'sd172700 , cz:32'sd387507 , radius:32'sd32768  , colorR:8'd128, colorG:8'd128, colorB:8'd128, reflectivity:32'sd32768 }
    };

    localparam light_t LIGHTS [0:NUM_LIGHTS-1] = '{
        '{ lx:-32'sd115763, ly:32'sd256614  , lz:32'sd194818 , colorR:8'd255, colorG:8'd245, colorB:8'd230, intensity:32'sd98304   }
    };

endpackage

`default_nettype wire
