// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VtbGenericVga.h for the primary calling header

#ifndef VERILATED_VTBGENERICVGA___024ROOT_H_
#define VERILATED_VTBGENERICVGA___024ROOT_H_  // guard

#include "verilated.h"


class VtbGenericVga__Syms;

class alignas(VL_CACHE_LINE_BYTES) VtbGenericVga___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock50MHz,0,0);
        VL_IN8(resetn,0,0);
        VL_OUT8(hSync,0,0);
        VL_OUT8(vSync,0,0);
        VL_OUT8(visible,0,0);
        VL_OUT8(red,7,0);
        VL_OUT8(green,7,0);
        VL_OUT8(blue,7,0);
        CData/*0:0*/ tbGenericVga__DOT__pixelVisible;
        CData/*0:0*/ tbGenericVga__DOT__pixelClk;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__spi_select_ROM;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__spi_enter_quadmode;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__spi_start_read;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__spi_start_write;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__spi_stop_txn;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__spi_data_req;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__spi_at_quadmode;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__vsfs_start_read;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__vsfs_start_write;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__vsfs_stop_txn;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__do_swap;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__start_vsfs;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__has_tex;
        CData/*4:0*/ tbGenericVga__DOT__dut__DOT__fsm_state;
        CData/*4:0*/ tbGenericVga__DOT__dut__DOT__read_delay;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT__sub_frame;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__evenframe;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__display_start_read;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__display_start_write;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__display_stop_txn;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__vsfs_running;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__ram_notbusy;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT__gamepad_input;
        CData/*3:0*/ tbGenericVga__DOT__dut__DOT____Vlvbound_hfc7abb36__0;
        CData/*3:0*/ tbGenericVga__DOT__dut__DOT____Vlvbound_hfc7abb36__1;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__driver__DOT__driver__DOT__pmod_clk_prev;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__driver__DOT__driver__DOT__pmod_latch_prev;
        CData/*1:0*/ tbGenericVga__DOT__dut__DOT__driver__DOT__driver__DOT__pmod_data_sync;
        CData/*1:0*/ tbGenericVga__DOT__dut__DOT__driver__DOT__driver__DOT__pmod_clk_sync;
        CData/*1:0*/ tbGenericVga__DOT__dut__DOT__driver__DOT__driver__DOT__pmod_latch_sync;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div_start;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div_done;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2_start;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2_done;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul_start;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul_done;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul_busy;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot_start;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot_done;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__fsm_state;
        CData/*4:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__read_delay;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v0_u;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v0_v;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v1_u;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v1_v;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v2_u;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v2_v;
        CData/*1:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__tri_color;
        CData/*3:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__shade_color;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__pixel_u8;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__db_texel;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__manualRot;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__translate_z;
        CData/*3:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT____Vlvbound_h0af86799__0;
    };
    struct {
        CData/*3:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT____Vlvbound_h0af86799__1;
        CData/*6:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT__i;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT__sig_diff;
        CData/*2:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT__state;
        CData/*6:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT__i;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT__sig_diff;
        CData/*2:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT__state;
        CData/*4:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul__DOT__count;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul__DOT__almost_done;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul_start;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul_done;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul_busy;
        CData/*2:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__state;
        CData/*3:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul2__DOT__count;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul2__DOT__almost_done;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__sine_rom1__DOT__mem;
        CData/*2:0*/ tbGenericVga__DOT__dut__DOT__i_spi__DOT__fsm_state;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__i_spi__DOT__doing_quadmode;
        CData/*0:0*/ tbGenericVga__DOT__dut__DOT__i_spi__DOT__is_writing;
        CData/*7:0*/ tbGenericVga__DOT__dut__DOT__i_spi__DOT__spi_miso_buf_n;
        CData/*3:0*/ tbGenericVga__DOT__dut__DOT__i_spi__DOT__data;
        CData/*4:0*/ tbGenericVga__DOT__dut__DOT__i_spi__DOT__bits_remaining;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock50MHz__0;
        CData/*0:0*/ __VactContinue;
        VL_OUT16(xOrd,9,0);
        VL_OUT16(yOrd,9,0);
        SData/*9:0*/ tbGenericVga__DOT__xCounter;
        SData/*9:0*/ tbGenericVga__DOT__yCounter;
        SData/*9:0*/ tbGenericVga__DOT__dut__DOT__numtri;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT__i_numtri_byte;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT__numtri_byte;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT__numtri_byte_tex;
        SData/*9:0*/ tbGenericVga__DOT__dut__DOT__v__DOT__xc;
        SData/*9:0*/ tbGenericVga__DOT__dut__DOT__v__DOT__yc;
        SData/*11:0*/ tbGenericVga__DOT__dut__DOT__driver__DOT__gamepad_pmod_data;
        SData/*11:0*/ tbGenericVga__DOT__dut__DOT__driver__DOT__driver__DOT__shift_reg;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v1_x;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v1_y;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v1_z;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v1_w;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v2_x;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v2_y;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v2_z;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v2_w;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot_result;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_00;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_01;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_02;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_03;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_10;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_11;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_12;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_13;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_20;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_21;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_22;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_23;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_30;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_31;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_32;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__M_33;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_00;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_01;
    };
    struct {
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_02;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_03;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_10;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_11;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_12;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_13;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_20;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_21;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_22;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_23;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_30;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_31;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_32;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__MVP_33;
        SData/*9:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__tri_idx;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__x_model_v0;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__x_model_v1;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__x_model_v2;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__y_model_v0;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__y_model_v1;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__y_model_v2;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_model_v0;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_model_v1;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_model_v2;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__x_clip_v0;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__x_clip_v1;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__x_clip_v2;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__y_clip_v0;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__y_clip_v1;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__y_clip_v2;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_clip_v0;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_clip_v1;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_clip_v2;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__w_clip_v0;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__w_clip_v1;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__w_clip_v2;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__campos_x;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__campos_y;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__campos_z;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__nx;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__ny;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__nz;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__light_x;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__light_y;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__light_z;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__lightW_x;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__lightW_y;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__lightW_z;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__lightM_x;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__lightM_y;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__lightM_z;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__viewdir_x;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__viewdir_y;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__viewdir_z;
        SData/*9:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__pixel_y;
        SData/*9:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__pixel_x;
        SData/*8:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__rotY_angle;
        SData/*8:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__rotY_angle_90;
        SData/*8:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__rotX_angle;
        SData/*8:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__rotX_angle_90;
        SData/*8:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__rotY_light;
        SData/*8:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__rotY_light_90;
        SData/*8:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__sine_angle;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__cosTheta;
    };
    struct {
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__sinTheta;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__cosPhi;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__sinPhi;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__cosLight;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__sinLight;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__cosTheta_sinPhi;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__sinTheta_cosPhi;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__cosTheta_cosPhi;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__sinTheta_sinPhi;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__sinTheta_Tz;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__cosTheta_sinPhi_Tz;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__cosTheta_cosPhi_Tz;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul_a;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul_b;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__tmp_vs_mul1;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul2__DOT__p_a;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul2__DOT__p_b;
        SData/*15:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul2__DOT__pwire;
        IData/*17:0*/ tbGenericVga__DOT__dut__DOT__numread;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div_a;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div_b;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div_result;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul_a;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul_b;
        IData/*17:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__numread;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__x_screen_v0;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__x_screen_v1;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__x_screen_v2;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__y_screen_v0;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__y_screen_v1;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__y_screen_v2;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_screen_v0;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_screen_v1;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_screen_v2;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bboxMin_X;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bboxMin_Y;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bboxMax_X;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bboxMax_Y;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__e0_init;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__e1_init;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__e2_init;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__tmp_ei_mul1;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__tmp_ei_mul2;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__denom;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bar_ix;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bar_ix_dx;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bar_ix_dy;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bar_iy;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bar_iy_dx;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bar_iy_dy;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bar_iz;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bar_iz_dx;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__bar_iz_dy;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_bar;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_bar_dx;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__z_bar_dy;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__u_bar;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__u_bar_dx;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__u_bar_dy;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v_bar;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v_bar_dx;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__v_bar_dy;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__pixel_z;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__pixel_u;
    };
    struct {
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__pixel_v;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__e0;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__e1;
        IData/*19:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__e2;
        IData/*30:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT__au;
        IData/*30:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT__bu;
        IData/*30:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT__quo;
        IData/*30:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT__quo_next;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT__acc;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT__acc_next;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT____Vconcswap_1_hfa6d15fc__0;
        IData/*30:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div1__DOT____Vconcswap_1_hfa6d5e4a__0;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul__DOT__p_a;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul__DOT__p_b;
        IData/*21:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul__DOT__pwire;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul_result;
        IData/*31:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__dot__DOT__mul2__DOT__partial;
        IData/*31:0*/ __VactIterCount;
        QData/*39:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2_a;
        QData/*39:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2_b;
        QData/*39:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2_result;
        QData/*43:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul_result;
        QData/*38:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT__au;
        QData/*38:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT__bu;
        QData/*38:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT__quo;
        QData/*38:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT__quo_next;
        QData/*39:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT__acc;
        QData/*39:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT__acc_next;
        QData/*39:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT____Vconcswap_1_heb8cd72c__0;
        QData/*38:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__div2__DOT____Vconcswap_1_heb8ccd80__0;
        QData/*43:0*/ tbGenericVga__DOT__dut__DOT___vsfs__DOT__mul__DOT__partial;
        VlUnpacked<CData/*3:0*/, 6> tbGenericVga__DOT__dut__DOT__pixels;
        VlUnpacked<SData/*15:0*/, 14> tbGenericVga__DOT__dut__DOT___vsfs__DOT__tri_xyz;
        VlUnpacked<CData/*3:0*/, 4> tbGenericVga__DOT__dut__DOT___vsfs__DOT__texel;
        VlUnpacked<CData/*7:0*/, 4> tbGenericVga__DOT__dut__DOT___vsfs__DOT__Z_buffer;
        VlUnpacked<CData/*3:0*/, 4> tbGenericVga__DOT__dut__DOT___vsfs__DOT__C_buffer;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    VtbGenericVga__Syms* const vlSymsp;

    // CONSTRUCTORS
    VtbGenericVga___024root(VtbGenericVga__Syms* symsp, const char* v__name);
    ~VtbGenericVga___024root();
    VL_UNCOPYABLE(VtbGenericVga___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
