import pathlib
out = pathlib.Path("c:/Users/Roshan/Documents/ttsky-asic/cordic/tb_vector_normalization.sv")
L = []
A = L.append
A("// ModelSim testbench for vector_normalization")
A("// Compile: vlog vectoring.sv rotation.sv vector_normalization.sv tb_vector_normalization.sv")
A("// Simulate: vsim -c tb_vector_normalization -do " + chr(34) + "run -all; quit" + chr(34))
A("//")
A("// Checks:")
A("//   1. Output magnitude ~= 1.0  (unit vector)")
A("//   2. Output direction matches input  (cosine similarity ~= 1.0)")
A("//   3. ID tracking: out_id matches expected ID per transaction")
A("//")
A("// Pipeline latency: 44 cycles (4 x 11-cycle CORDIC stages)")
A("")
A(chr(96) + "timescale 1ns/1ps")
A("")
A("module tb_vector_normalization;")
A("")
A("    // DUT signals")
A("    logic        clock;")
A("    logic        reset;")
A("    logic signed [11:0] x_in, y_in, z_in;")
A("    logic [7:0]  in_id;")
A("    logic signed [11:0] x_norm, y_norm, z_norm;")
A("    logic [7:0]  out_id;")
A("")
A("    // Parameters")
A("    parameter real FIXED_SCALE      = 256.0;")
A("    parameter int  PIPELINE_LATENCY = 44;")
A("    parameter int  NUM_TESTS        = 12;")
A("    parameter real TOLERANCE_MAG    = 0.10;")
A("    parameter real TOLERANCE_DIR    = 0.05;")
A("")
A("    // Test bookkeeping")
A("    int test_count;")
A("    int pass_count;")
A("    int fail_count;")
A("")
A("    // Test vector type")
A("    typedef struct {")
A("        real   x_real;")
A("        real   y_real;")
A("        real   z_real;")
A("        string name;")
A("        real   expected_magnitude;")
A("    } test_vector_t;")
A("")
A("    test_vector_t test_vectors[NUM_TESTS];")
A("")
A("    // DUT instantiation")
A("    vector_normalization #(.ID_WIDTH(8)) dut (")
A("        .clock  (clock),")
A("        .reset  (reset),")
A("        .x_in   (x_in),")
A("        .y_in   (y_in),")
A("        .z_in   (z_in),")
A("        .in_id  (in_id),")
A("        .x_norm (x_norm),")
A("        .y_norm (y_norm),")
A("        .z_norm (z_norm),")
A("        .out_id (out_id)")
A("    );")
A("")
A("    // Clock: 10 ns period (100 MHz)")
A("    initial begin")
A("        clock = 0;")
A("        forever #5 clock = ~clock;")
A("    end")
A("")
A("    // Helper: real -> Q4.8")
A("    function automatic logic signed [11:0] real_to_q48(real value);")
A("        return " + chr(36) + "signed(" + chr(36) + "rtoi(value * FIXED_SCALE));")
A("    endfunction")
A("")
A("    // Helper: Q4.8 -> real")
A("    function automatic real q48_to_real(logic signed [11:0] value);")
A("        return " + chr(36) + "itor(" + chr(36) + "signed(value)) / FIXED_SCALE;")
A("    endfunction")
A("")
A("    // Helper: 3D magnitude")
A("    function automatic real compute_magnitude(real x, real y, real z);")
A("        return " + chr(36) + "sqrt(x*x + y*y + z*z);")
A("    endfunction")
A("")
A("    // Helper: absolute value")
A("    function automatic real abs_real(real value);")
A("        return (value < 0.0) ? -value : value;")
A("    endfunction")
A("")
A("    // Initialize test vectors")
A("    initial begin")
A("        // Axis-aligned")
A("        test_vectors[0].x_real = 1.0;  test_vectors[0].y_real = 0.0;  test_vectors[0].z_real = 0.0;")
A("        test_vectors[0].name = " + q + "+X axis (1,0,0)" + q + ";          test_vectors[0].expected_magnitude = 1.0;")
