// ─────────────────────────────────────────────────────────────────────────────
// scene_lut.sv  —  Compile-time scene LUT (4 spheres + 2 lights)
//
// Generated by Scene LUT Editor
// Matches c-implementation/scene.h exactly (Q16.16 values)
//
// Sphere encoding:
//   - center (cx, cy, cz)
//   - radius
//   - color (r, g, b) as 8-bit integers (0-255)
//   - reflectivity (Q16.16, 0.0 to 1.0)
//
// Light encoding:
//   - position (lx, ly, lz)
//   - color (r, g, b) as 8-bit integers (0-255)
//   - intensity (Q16.16, typically 1.5 = 98304)
// ─────────────────────────────────────────────────────────────────────────────

`timescale 1ns/1ps
`default_nettype none

package scene_lut;
    // Scene counts
    localparam NUM_SPHERES = 4;
    localparam NUM_LIGHTS  = 2;

    typedef struct packed {
        logic signed [31:0] cx, cy, cz;
        logic signed [31:0] radius;
        logic [7:0] colorR, colorG, colorB;
        logic signed [31:0] reflectivity;
    } sphere_t;

    typedef struct packed {
        logic signed [31:0] lx, ly, lz;
        logic [7:0] colorR, colorG, colorB;
        logic signed [31:0] intensity;
    } light_t;

    // Table-driven scene data (update this section only)
    localparam sphere_t SPHERES [0:NUM_SPHERES-1] = '{
        '{ cx:-32'sd114688 , cy:32'sd0       , cz:32'sd393216 , radius:32'sd98304  , colorR:8'd255, colorG:8'd80 , colorB:8'd60 , reflectivity:32'sd42598   },
        '{ cx:32'sd114688  , cy:32'sd0       , cz:32'sd393216 , radius:32'sd98304  , colorR:8'd60 , colorG:8'd160, colorB:8'd255, reflectivity:32'sd42598   },
        '{ cx:32'sd0       , cy:-32'sd262144 , cz:32'sd425984 , radius:32'sd196608 , colorR:8'd220, colorG:8'd220, colorB:8'd220, reflectivity:32'sd9830    },
        '{ cx:32'sd72367   , cy:32'sd0       , cz:32'sd746135 , radius:32'sd65536  , colorR:8'd17 , colorG:8'd255, colorB:8'd0  , reflectivity:32'sd32768   }
    };

    localparam light_t LIGHTS [0:NUM_LIGHTS-1] = '{
        '{ lx:32'sd0      , ly:32'sd16079   , lz:32'sd556734 , colorR:8'd255, colorG:8'd153, colorB:8'd0  , intensity:32'sd98304   },
        '{ lx:32'sd0      , ly:32'sd191576  , lz:32'sd239270 , colorR:8'd238, colorG:8'd255, colorB:8'd0  , intensity:32'sd65536   }
    };

endpackage

`default_nettype wire
